### ISSUE TITLE
Error running move unit test with initiad

### ISSUE THREAD

**Issue by dev8723** [initia-labs/initia-tutorials#4]
Hi @beer-1 @JSHan94 @ALPAC-4 I'm following the tutorial to run unit test for managed coin but i got these errors.

Clone the repo without any change, run `initiad move test --path move/managed_coin --dev` gives `failure occurred from compiler: failed to test: Unable to resolve packages for package 'managed_coin'`.

After clearing  the `your_address` in `addresses` in move.toml and only set it in `dev-addresses`, I can compile but getting 

```sh
┌── test_create_and_mint ──────
│ error[E11001]: test failure
│     ┌─ /Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/account.move:117:16
│     │
│ 117 │     native fun request_create_account(addr: address, account_type: u8): u64;
│     │                ^^^^^^^^^^^^^^^^^^^^^^
│     │                │
│     │                INTERNAL TEST ERROR: INTERNAL VM INVARIANT VIOLATION.
│ Test was not expected to error, but it gave a INTERNAL_TYPE_ERROR (code 2009) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::account rooted here
│     │                In this function in 0x1::account
│
│
│ stack trace
│ 	table::new(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/table.move:34)
│ 	primary_fungible_store::init_module(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/fa/primary_fungible_store.move:47)
│ 	primary_fungible_store::init_module_for_test(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/fa/primary_fungible_store.move:295)
│ 	managed_coin::test_create_and_mint(./sources/managed_coin.move:58)
│
└──────────────────
```

I also created a launchpad contract to learn move, but i run into same error when calling `primary_fungible_store::init_module_for_test(chain);` in my unit test. 

[Source code of my contract](https://github.com/bull-market-lab/move-launchpad/blob/main/contract/sources/coin_launchpad.move#L197)

My initiad version
```sh
build_tags: netgo,ledger
commit: 867edd537d3ea47ddbd299e292b144c7b6e3f3b5
cosmos_sdk_version: v0.0.0-20240425031032-6bc18cf6e67d
go: go version go1.22.4 darwin/amd64
name: initia
server_name: initiad
version: v0.3.1
```

**Comment by dev8723** [comment]
I think this is a problem with initiad, I run unit test with `@initia/builder.js` 0.1.6 and it works fine. 

[Script source code](https://github.com/bull-market-lab/move-launchpad/blob/main/node_script/test_contract.ts).

**Comment by dev8723** [comment]
I built initiad at different commit history of initia repo, when [this commit](https://github.com/initia-labs/initia/pull/139/files) is applied, the error happened. If I manually set movevm to 0.2.7, the error is gone, so some change in movevm 0.2.8 broke it.

**Comment by ALPAC-4** [comment]
Hi @llllllluc . Sorry for the late reply. I just updated [move-natives](https://github.com/initia-labs/move-natives) repository to a version suitable for initiation-1. Can you rebuild and retest it?

**Comment by JSHan94** [comment]
@llllllluc  fyi, it seems like your [contract](https://github.com/DAO-C-DAO/move-launchpad/blob/main/contract/Move.toml) using main repo.
```
[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives", subdir = "initia_stdlib", rev = "main" }
```
rev tag should match with initiad version. so if you wanna use main rev, then you should also upgrade your initiad as main.
builder.js v0.1.6 is supporting initiation-1 now.

**Comment by dev8723** [comment]
Thanks for taking a look, I rebuilt initiad with latest main (commit: `9af2a797df0c93e706d261535647787f0d38c5a8`), re-run unit test of `managed_coin` in this tutorial repo, now I'm getting a different error. Btw I set `move-natives` to latest main and I'm NOT using `--skip-fetch-latest-git-deps` so `move-natives` should be up to date.

```sh
INCLUDING DEPENDENCY InitiaStdlib
INCLUDING DEPENDENCY MoveNursery
INCLUDING DEPENDENCY MoveStdlib
BUILDING managed_coin
Running Move unit tests
[ FAIL    ] 0x2::managed_coin::test_create_and_mint

Test failures:

Failures in 0x2::managed_coin:

┌── test_create_and_mint ──────
│ error[E11001]: test failure
│     ┌─ /Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/account.move:123:23
│     │
│ 123 │     native public fun get_account_info(addr: address): (bool /* found */, u64 /* account_number */, u64 /* sequence_number */, u8 /* account_type */);
│     │                       ^^^^^^^^^^^^^^^^
│     │                       │
│     │                       INTERNAL TEST ERROR: Unexpected Verification Error
│ Test was not expected to error, but it gave a MISSING_DEPENDENCY (code 1021) error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::account rooted here
│     │                       In this function in 0x1::account
│
│
│ stack trace
│ 	table::new(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/table.move:34)
│ 	primary_fungible_store::init_module(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/fa/primary_fungible_store.move:47)
│ 	primary_fungible_store::init_module_for_test(/Users/dev0/.move/https___github_com_initia-labs_move-natives_main/initia_stdlib/sources/fa/primary_fungible_store.move:295)
│ 	managed_coin::test_create_and_mint(./sources/managed_coin.move:58)
│
└──────────────────
```

**Comment by dev8723** [comment]
Ah Ok if I use `initiation-1` branch of `initia` repo to build `initiad`, I can pass unit test.

**Comment by Vritra4** [comment]
then everything is ok now?

**Comment by dev8723** [comment]
> then everything is ok now?

@Vritra4  Yeah I think we just need to mention somewhere that devs should use initiation-1 branch instead of main to build initiad. If you can open source the doc repo, I can make a PR.

**Comment by JSHan94** [comment]
@llllllluc  for now, we don't open the docs repo. we will update docs as you suggested. if you don't need additional help, could you close issue please?
